### ISSUE TITLE
Split Failure only looks back 30 minutes for Detector 

### ISSUE THREAD

**Issue by udotdevelopment** [udotdevelopment/ATSPM#1]
Example: SIG#6054 on 2/22/2017, Ph7. Detector ON at 7:58:04 PM and next OFF at 9:41:07 PM. Split Failure shows only 30 minuets of Split Fails. Then it shows 0% GOR and ROR when it should show 100%. I'm assuming the algorithm only looks for detector events 30 m
[Bug_SplitFail.pdf](https://github.com/udotdevelopment/ATSPM/files/1268135/Bug_SplitFail.pdf)
inutes previous. See attached.

**Comment by shanejohnson-udot** [comment]
Derek fixed this.
