### ISSUE TITLE
Canceling Create New Signal dialog creates (null) signal

### ISSUE THREAD

**Issue by ian-cameron** [udotdevelopment/ATSPM#18]
This is a minor thing when using the new Online Signal Configuration tool.  The link to 'Create New Signal' will create a signal with the specified ID if you click OK in the popup dialog box.  However, if you click Cancel in that dialog it will still create a signal, but with null ID.

**Comment by shanejohnson-udot** [comment]
I merged this into the "cycles and plans" branch we have been working on.
