### ISSUE TITLE
The object 'DF__ApproachP__Total__762C88DA' is dependent on column 'TotalDelay'.

### ISSUE THREAD

**Issue by oschwartz10612** [udotdevelopment/ATSPM#192]
Hi,

I have spun up a fresh Windows server and tried to install 4.3, but I get the error `The object 'DF__ApproachP__Total__762C88DA' is dependent on column 'TotalDelay'.` After swapping out the server for 4.2.4, it loads no problem.

Is this a bug in the latest version?

Best,
Owen

**Comment by avetraffic** [comment]
This is the same issue discussed in #157. 
We'll be releasing a patch sometime this week or next.
