### ISSUE TITLE
GenerateAddData Script and other scripts missing or only have debug folders in 4.3.1

### ISSUE THREAD

**Issue by AndrewMC6** [udotdevelopment/ATSPM#212]
### Discussed in https://github.com/udotdevelopment/ATSPM/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **AndrewMC6** February 24, 2023</sup>
Hello,

Working through a new installation, however it appears that the GenerateAddDataScript folder in section 2.6 of the installation manual, has a few sub-folders but they are all empty? Any insight would be helpful. Thanks!</div>

_Moved from discussion to issue, closed previous duplicate issue I'd created. My github skills are novice at best_ :)

**Comment by avetraffic** [comment]
It looks like an small pathing issue was preventing it from being added in the release. Thanks for noticing that. We've added it.
