### ISSUE TITLE
ATSPM with simulated intersection using Econolite Cobalt

### ISSUE THREAD

**Issue by piromel** [udotdevelopment/ATSPM#218]
I am a grad student working on some research and would like some help in my simulation of a field intersection and getting data for a connected ATSPM website. This video (https://www.youtube.com/embed/DyEVrmncV5I) shows what I have so far, which I will describe below:

- I have an Econolite Cobalt controller with no other external hardware. I'm in Tennessee so it is set to Mode 1.
- I know just a little of how the controller works, like the output for the RYG lights for each phase provides 24V, and the detector also with 24V output, registers a call on the controller when connected to the ground pin.
- I have used a simple circuit with LEDs, resistors, and a NOR gate IC chip to provide the signaling for a simulated intersection as seen in the linked video.
- The blue LEDs are connected to emulate detection along the through phases (2/4/6/8): a transistor is provided with high/low voltage at its base and it acts as a switch connecting the detector pin to the ground. The goal is to try to emulate stop bar detection and advance detection for speed and count.

The website is not registering any of the data as detector data. The crux of the matter is, what should I do to 'make' it see the data, and distinguish that one is stop bar data and the other is advance speed/count? Is what I am trying to do with this simulation even possible?

1. On the side of the controller, is there anything I must configure to distinguish between the sets of data? I am using detectors 2, 4, 6 & 8 for the stop bars and 1, 3, 5 & 7 for advance detection for phases 2, 4, 6 & 8 respectively.
2. On the side of the website, does the entry for 'detector channel' translate to the detector number? Will the detector channel input for the stop bar on phase 2 be '2'?

EDIT: I figured things out. It was mostly controller settings that I had to configure and I got an expert to assist!!

Thanks,
Piro Meleby.

**Comment by avetraffic** [comment]
Awesome! Glad you able to get it working.
