### ISSUE TITLE
Custom MOE Width

### ISSUE THREAD

**Issue by Derek-Lehrke** [udotdevelopment/ATSPM#23]
Is there a method for setting the size of the Metric Output Graphs? I would like to generate some 24hour graphs but given the multiple patterns the info at the top (Num of skips, Plan Num, etc.) gets cut off.

Split Monitor Metrics appears to be set to 740x500, Purdue Phase Termination 1100 x 550, etc.

**Comment by udotdevelopment** [comment]
There is not a way to set the size.
