### ISSUE TITLE
Why can't ATSPM Software Support Port forwarding?

### ISSUE THREAD

**Issue by Madmandrd** [udotdevelopment/ATSPM#28]
Other central and or ATMS software programs support port forwarding. And if Udot's software is open source why can't the SQL server be configured to support Dynamic ports? Cell Modem use and Layer 3 switching. Is on the increase. In Traffic Network Deployments and they need to be supported. I think this the most practical solution.

**Comment by shanejohnson-udot** [comment]
I think it is a great idea.  Many agencies need that feature.  You should update the source code to support port forwarding.  UDOT doesn't require that technology, so it is not on our development road map.
