### ISSUE TITLE
Command Timeout

### ISSUE THREAD

**Issue by Derek-Lehrke** [udotdevelopment/ATSPM#31]
While working to diagnose several exception errors I found that they all originated from the following error. 

`"Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding."`

Since MnDOT compressed its data using ColumnStore the queries were failing due to there not being enough resources (CPU/RAM) before the default value for "CommandTimeout" in the database connection object expired.

Until more resources are allocated I worked around it by  adding ` Database.CommandTimeout = 300;`
between lines 18 and 19. 

https://github.com/udotdevelopment/ATSPM/blob/9d25d14a914e7d5c1796a591a5b5d5af61742ac4/MOE.Common/Models/SPM.cs#L15-L24

**Comment by udotdevelopment** [comment]
This pull request has been incorporated.
