### ISSUE TITLE
Issue installing ATSPM 4.2

### ISSUE THREAD

**Issue by MorenoJu** [udotdevelopment/ATSPM#42]
Hi all,
When installing ATSPM 4.2, I ran into the following error:

Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.  

Do you have any suggestion on what to do?

Thanks

**Comment by udotdevelopment** [comment]
Let me take look. Can you tell what the last entry in the _MigrationHistory table is?

**Comment by udotdevelopment** [comment]
Also would you mind telling me what the name of the primary key on your signals table is?

**Comment by udotdevelopment** [comment]
Ok. I think I have it fixed now and I have updated the executable for the database conversion on GitHub. Can you try it again?

**Comment by MorenoJu** [comment]
Sounds good. We’ll get back to you when we’ve tried it. Thanks!

**Comment by MorenoJu** [comment]
Hi,

We tried the new code and yes, it is fixed. It created the database with content in the tables. We can continue with the rest of the installation now.

Thanks for the quick response!

**Comment by MorenoJu** [comment]
We downloaded the updated version and we were able to continue with the installation.
Thanks for the support.
