### ISSUE TITLE
The Website only displaying broken icons not the full chart

### ISSUE THREAD

**Issue by shoaibmahmud** [udotdevelopment/ATSPM#54]
Hello everyone. I hope everyone is doing great. I am trying to install ATSPM website. I am now at step 2.7 ( create web service).  However, when I am trying to create the default chart, the website is only showing the charts as broken Icon ( not the actual chart) ( like the following figure). But in the directory folder ( SPMImage folder), I can see the created images/metrics. 
Do you have any idea, how to fix that issue/ why this is happening? Thanks in advance. 
![ATSPM_Problem_1](https://user-images.githubusercontent.com/25102689/56309228-b8d64f80-610e-11e9-8a61-4ad3e8f04a81.JPG)

**Comment by shanejohnson-atspm** [comment]
Check the ImageUrl setting in the ApplicationSettings table in the database.  Make sure it matches the virtual directory that you set up in IIS.
