### ISSUE TITLE
Errors when trying to FTP to controllers

### ISSUE THREAD

**Issue by AndrewMC6** [udotdevelopment/ATSPM#57]
Hi all,

After working my way through the setup process I finally have ATSPM running, the website is working, however whenever I try to make report the charts are all blank. When I try to FTP to all controllers (all econolite cobalts) it see lots of errors in the command prompt output, which is attached. It almost looks like the controller is rejecting the FTP connection? 
[spmFTPErrors.txt](https://github.com/udotdevelopment/ATSPM/files/3139548/spmFTPErrors.txt)

Any help appreciated.

**Comment by shanejohnson-atspm** [comment]
They look like SNMP errors.
You should check to see that SNMP is enabled through your firewall, and that your controllers are listening for SNMP messages on the same port you have set to send them.
