### ISSUE TITLE
ATSPM Setup Scenario

### ISSUE THREAD

**Issue by mebouret** [udotdevelopment/ATSPM#62]
We would like to setup the following architecture – web server in the DMZ and production server in the protected traffic VLAN.  Give the web server access to a file share with the reports / charts, but otherwise keep it with limited access back to our traffic server. 

It looks like the documentation states you can install the different components on different servers, but there isn’t much guidance on how to set this up or the drawbacks. Just curious if anyone has done this and how it worked or any ‘gotchas’ discovered trying to separate this out.

Thanks!

**Comment by udotdevelopment** [comment]
At UDOT we have it set up similar to this. It works pretty well. The main hurtle is getting the correct protocols set up on the firewall to allow the different servers to talk to each other.
