### ISSUE TITLE
Incorporate code to fix Link Pivot problem with multiple detectors

### ISSUE THREAD

**Issue by udotdevelopment** [udotdevelopment/ATSPM#7]
Kittleson has fixed this issue in the code and posted it to the OSADP forum.

**Comment by ian-cameron** [comment]
https://github.com/udotdevelopment/ATSPM/pull/14

**Comment by udotdevelopment** [comment]
Kittleson has submitted a fix for this through a pull request. This has been accepted into the master branch.
