### ISSUE TITLE
Link Pivot Reports

### ISSUE THREAD

**Issue by ian-cameron** [udotdevelopment/ATSPM#70]
Issue 1: Arrival on Green (AOG) charts are not cyclical. The AOGs at the maximum adjustment values are all near zero.
![image](https://user-images.githubusercontent.com/5150870/65616596-26b15d80-df70-11e9-988d-870ebf62e936.png)

Issue 2: When using “Upstream” as the Starting Point, the link approaches are assigned one intersection off and upstream/downstream are reversed.
![image](https://user-images.githubusercontent.com/5150870/65617440-9c69f900-df71-11e9-953c-1a11e29c3ed6.png)

Issue 3: Numbers reported for Existing AOGs (in Link Pivot) do not match results from Purdue Coordination Diagram charts for the same signal.   The PCD chart is counting arrivals on Yellow and Green, and Link Pivot only count arrivals on Green.  Either method is valid, but for consistency we should probably be using the same calculation for counting arrivals on green in all reports.

**Comment by runneals** [comment]
This should be closed
