### ISSUE TITLE
ATSPM + SFTP Support

### ISSUE THREAD

**Issue by markKHA** [udotdevelopment/ATSPM#99]
Has anyone used SFTP to get data off controllers? We are working with some Commander controllers running Trafficware that have FTP disabled, but SFTP enabled. We understand that ATSPM doesn't support STFP right now, but we're curious if any agencies have developed a workaround.

**Comment by markKHA** [comment]
Hi Yi,

Can you tell me what the 'RenameDatFiles' function does?

**Comment by markKHA** [comment]
Just wanted to follow up on this and get some clarity on what the 'RenameDatFiles' function does.

**Comment by ychehntb** [comment]
@markKHA Hi Mark, sorry for get back to you late. The "RenameDatFiles" function are some customization FDOT does as we deal with some controller cabinet files which are not named in .dat coming out of SFTP. I believe you can comment out this function as it doesn't affect any of the SFTP polling function. Hope it helps.

Yi
